# -*- coding: utf-8 -*-
"""LSTM, deep learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13s4qJc-Mpwem3AOmF0gPW0z5kqtyAV9D
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import LSTM, Dense

"""Load the Dataset"""

df = pd.read_csv("AirPassengers.csv")
df.columns = ["Month", "Passengers"]
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)

"""Standardize the Data"""

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df)

"""Sequence Creation

"""

def create_sequences(data, seq_length):
    X, y = [], []
    for i in range(seq_length, len(data)):
        X.append(data[i-seq_length:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)

sequence_length = 12
X, y = create_sequences(scaled_data, sequence_length)

"""Reshape"""

X = np.reshape(X, (X.shape[0], X.shape[1], 1))

"""Model Building"""

model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X.shape[1], 1)))
model.add(LSTM(units=50))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X, y, epochs=50, batch_size=16, verbose=1)

"""Forcasting Next Twelve Months"""

last_sequence = scaled_data[-sequence_length:]
forecast = []

input_seq = last_sequence.copy()
for _ in range(12):
    pred = model.predict(input_seq.reshape(1, sequence_length, 1), verbose=0)
    forecast.append(pred[0, 0])
    input_seq = np.append(input_seq[1:], [[pred[0, 0]]], axis=0)

"""Transforming Back To Original Scale"""

forecast = scaler.inverse_transform(np.array(forecast).reshape(-1, 1))

"""Ploting The Result"""

forecast_index = pd.date_range(start=df.index[-1] + pd.DateOffset(months=1), periods=12, freq='MS')
forecast_df = pd.DataFrame(forecast, index=forecast_index, columns=["Forecast"])

plt.figure(figsize=(12, 6))
plt.plot(df.index, df['Passengers'], label='Actual')
plt.plot(forecast_df.index, forecast_df['Forecast'], label='Forecast', color='red')
plt.xlabel('Date')
plt.ylabel('Number of Passengers')
plt.title('Air Passengers Forecast using LSTM')
plt.legend()
plt.grid(True)
plt.show()